program Dressed_Ref_Hamiltonian  implicit none
  BEGIN_DOC
! TODO
  END_DOC
  print *, '  _/                              '
  print *, ' -:\_?,     _Jm####La             '
  print *, 'J"(:" >  _]#AZ#Z#UUZ##,           '
  print *, '_,::./   %(|i%12XmX1*1XL      _?, '
  print *, '  \..\ _\(vmWQwodY+ia%lnL  _",/ ( '
  print *, '   .:< ]J=mQD?WXn<uQWmmvd, -.-:=!'
  print *, '   "{Z jC]QW|=3Zv)Bi3BmXv3  =   _7'
  print *, '    ]h[Z6)WQ;)jZs]C;|$BZv+, : ./  '
  print *, '    -#sJX%$Wmm#ev]hinW#Xi:` c ;   '
  print *, '     #X#X23###1}vI$WWmX1>|,)nr"   '
  print *, '     4XZ#Xov1v}=)vnXAX1nnv;1n"    '
  print *, '     ]XX#ZXoovvvivnnnlvvo2*i7     '
  print *, '     "23Z#1S2oo2XXSnnnoSo2>v"     '
  print *, '      miX#L -~`""!!1}oSoe|i7      '
  print *, '      4cn#m,        v221=|v[      '
  print *, '      ]hI3Zma,;..__wXSe=+vo       '
  print *, '      ]Zov*XSUXXZXZXSe||vo2       '
  print *, '      ]Z#><iiii|i||||==vn2(       '
  print *, '      ]Z#i<ii||+|=||=:{no2[       '
  print *, '      ]ZUsiiiiivi|=||=vo22[       '
  print *, '      ]XZvlliiIi|i=|+|vooo        '
  print *, '      =v1llli||||=|||||lii(       '
  print *, '      ]iillii||||||||=>=|<        '
  print *, '      -ziiiii||||||+||==+>        '
  print *, '       -%|+++||=|=+|=|==/         '
  print *, '        -a>====+|====-:-          '
  print *, '          "~,- --   /-            '
  print *, '            -.     )>             '
  print *, '           .~      +-             '
  print *, '           . .... : .             '
  print *, '            -------~              '
  print *, ''
end
