# Define here all new external source files and objects.Don't forget to prefix the
# object files with IRPF90_temp/
SRC=bitmasks_module.f90
OBJ=IRPF90_temp/bitmasks_module.o

include $(QPACKAGE_ROOT)/src/Makefile.common
