# Define here all new external source files and objects.Don't forget to prefix the
# object files with IRPF90_temp/
SRC=map_module.f90
OBJ=IRPF90_temp/map_module.o

include $(QPACKAGE_ROOT)/src/Makefile.common
